### ISSUE TITLE
Create Actuator Code

### ISSUE THREAD

**Issue by connorgannaway** [RoboKomodos/Archimedes#10]
Create code that runs the actuator

**Comment by cgannaway** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create the actuator code.](https://trello.com/c/mo9R8aoD/13-create-the-actuator-code)

**Comment by connorgannaway** [comment]
Heads up, you will need to use timed commands for this. One timed command for making the actuator move forward, and one to make it go back. Run both of them from a command group. @C0de5mith
