### ISSUE TITLE
Create Launch Motor Code

### ISSUE THREAD

**Issue by connorgannaway** [RoboKomodos/Archimedes#9]
Create code that runs the two launch motors.

**Comment by cgannaway** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create the launch motor code.](https://trello.com/c/gmBiyvCq/14-create-the-launch-motor-code)

**Comment by cgannaway** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create the launch motor code.](https://trello.com/c/gmBiyvCq/14-create-the-launch-motor-code)
